// Pokemon/front-end/src/components/Footer.vue
<template>
  <div class="github">
    <div class="center">
      <a href="https://github.com/MayDevelops/WebProjects/tree/master/Pokemon">
        <img :src="require('../../public/GitHub-Mark-64px.png')" alt=""/>
      </a>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style>
.github {
  margin-top: 1rem;
  padding: 1rem;
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
}

.github img {
  border-radius: 50%;
  justify-content: center;
}

.center {
  justify-content: center;
  justify-items: center;
  text-align: center;
}
</style>

// ReactWebServer/Homepage/src/Components/Footer.jsx
import React from 'react';
import './Footer.css';
import GitHubLogo from '../images/GitHub-Mark-64px.png';

const Footer = () => {
    return (
        <div className="github">
            <div className="center">
                <a href="https://github.com/MayDevelops/WebProjects/tree/master/ReactWebServer/Homepage">
                <img src={GitHubLogo} alt=""/>

                </a>
            </div>
        </div>
    );
};

export default Footer;
